#cloud-config
# vim:syntax=yaml
runcmd:
- sudo apt update -y
- sudo apt install -y dnsutils
- sudo sysctl -w net.ipv4.ip_forward=1
- sudo sed -i -e "s/^#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf
- sudo iptables -F
- sudo iptables -I FORWARD 1 -i ens3 -o ens3 -j ACCEPT
- sudo iptables -t nat -A POSTROUTING -o ens3 -s 192.168.1.0/24 -j MASQUERADE
- sudo iptables -t nat -A PREROUTING -p tcp --dport 6443 -j DNAT --to-destination $(host oracle01.private.vcn01.oraclevcn.com | awk '{print $4}'):6443
- sudo iptables -t nat -A POSTROUTING -p tcp -d $(host oracle01.private.vcn01.oraclevcn.com | awk '{print $4}') --dport 6443 -j MASQUERADE
- sudo iptables -A FORWARD -p tcp ! --syn -m state --state ESTABLISHED -s $(host oracle01.private.vcn01.oraclevcn.com | awk '{print $4}') --sport 6443 -j ACCEPT
- sudo iptables -t nat -A OUTPUT -p tcp --dport 6443 -j DNAT --to-destination $(host oracle01.private.vcn01.oraclevcn.com | awk '{print $4}'):6443
