all:
  children:
    ubuntu:
      hosts:
        ubuntu01:
        ubuntu02:
        ubuntu03:
        ubuntu04:
      vars:
        ansible_ssh_user: ubuntu
        # ansible_ssh_private_key_file: ~/.ssh/id_rsa_oracle # for dev env

